In [30]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [31]:
df = pd.read_csv('data/train.txt', sep=';',header=None, names=['text','emotion'])

In [32]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [33]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [34]:
unique_emotions = df['emotion'].unique()

In [35]:
emotions_dict = {}
i = 0
for emotion in unique_emotions:
    emotions_dict[emotion] = i
    i += 1

df['emotion'] = df['emotion'].map(emotions_dict)
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

In [36]:
# convert to lower case
df['text'] = df['text'].apply(lambda x : x.lower())

In [37]:
#  remove punctutations
import string

def remove_punc(txt):
    return txt.translate(str.maketrans('','',string.punctuation))

In [38]:
df['text'] = df['text'].apply(remove_punc)
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

In [39]:
#remove  numbers
def remove_numbers(txt):
    new_txt =''
    for i in txt:
        if not i.isdigit():
            new_txt = new_txt + i
    return new_txt

In [40]:
df['text'] = df['text'].apply(remove_numbers)
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

In [41]:
# remove emojis and special characters
def remove_spcl(txt):
    new_txt =''
    for i in txt:
        if i.isascii():
            new_txt = new_txt + i
    return new_txt

In [42]:
df['text'] = df['text'].apply(remove_spcl)
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

In [43]:
import nltk

In [44]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [45]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Bitan\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Bitan\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Bitan\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [46]:
stop_words = set(stopwords.words('english'))
len(stop_words)

198

In [47]:
# Removing stopwords
def  remove_stopwords(txt):
    words = word_tokenize(txt)
    clean_txt = []
    for w in words:
        if not w in stop_words:
            clean_txt.append(w)
    return ' '.join(clean_txt)

In [48]:
df['text']= df['text'].apply(remove_stopwords)
df.head()

                                                text  emotion
0                              didnt feel humiliated        0
1  go feeling hopeless damned hopeful around some...        0
2          im grabbing minute post feel greedy wrong        1
3  ever feeling nostalgic fireplace know still pr...        2
4                                    feeling grouchy        1

In [49]:
from sklearn.model_selection import train_test_split

In [50]:
X_train, X_test, y_train, y_test = train_test_split(df['text'], df['emotion'], test_size=0.20, random_state=42)

In [64]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer

In [52]:
bow_vectoizer = CountVectorizer()

In [57]:
X_train_bow = bow_vectoizer.fit_transform(X_train)
X_test_bow = bow_vectoizer.transform(X_test)

In [58]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

In [59]:
nb_model = MultinomialNB()
nb_model.fit(X_train_bow,y_train)

MultinomialNB()

In [60]:
y_pred = nb_model.predict(X_test_bow)
accuracy_score(y_test, y_pred)

0.7678125

In [65]:
tf_idf_vectorizer = TfidfVectorizer()

In [66]:
X_train_tf = tf_idf_vectorizer.fit_transform(X_train)
X_test_tf = tf_idf_vectorizer.transform(X_test)

In [67]:
nb_model2 = MultinomialNB()

In [68]:
nb_model2.fit(X_train_tf, y_train)

MultinomialNB()

In [69]:
y_pred = nb_model2.predict(X_test_tf)
accuracy_score(y_test,y_pred)

0.6609375

In [70]:
from sklearn.linear_model import LogisticRegression

In [72]:
lr_model = LogisticRegression(max_iter=1000)

In [73]:
lr_model.fit(X_train_tf, y_train)

LogisticRegression(max_iter=1000)

In [74]:
y_pred = lr_model.predict(X_test_tf)

In [75]:
accuracy_score(y_test,y_pred)

0.8615625